<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Seller extends Model
{

    protected $primaryKey = 'user_id';

    protected $fillable = ['organization', 'occupation_id', 'rating'];

    public $timestamps = false;

    public function offers()
    {
        return $this->hasMany('App\Offers');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function occupation()
    {
        return $this->belongsTo('App\Occupation');
    }

    public function devices()
    {
        return $this->belongsToMany('App\Device', 'device_seller', 'seller_id', 'device_id', 'user_id');
    }


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($seller) {
            $seller->user()->delete();
        });
    }

}
